### ISSUE TITLE
plugin doesn't run when called by icinga

### ISSUE THREAD

**Issue by rduffner** [toubib/check-webpage#27]
I'm using this on an admittedly old version of Ubuntu (12) with a self-compiled version of icinga - but it does work when I run it with the icinga user.
However, when I use the check, this is returned:

```

  | [[BUG] rb_update_max_fd: invalid fd (0) given. ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]-- Control frame information -----------------------------------------------c:0001 p:---- s:0002 b:0002 l:000001 d:000001 TOP  -- C level backtrace information -------------------------------------------/usr/lib/libruby-1.9.1.so.1.9(+0x155c59) [0x7faa1a3d6c59]/usr/lib/libruby-1.9.1.so.1.9(+0x576e9) [0x7faa1a2d86e9]/usr/lib/libruby-1.9.1.so.1.9(rb_bug+0xb7) [0x7faa1a2d90d7]/usr/lib/libruby-1.9.1.so.1.9(+0x76414) [0x7faa1a2f7414]/usr/lib/libruby-1.9.1.so.1.9(+0x7d95f) [0x7faa1a2fe95f]/usr/lib/libruby-1.9.1.so.1.9(+0x7d9bd) [0x7faa1a2fe9bd]/usr/lib/libruby-1.9.1.so.1.9(+0x83dd1) [0x7faa1a304dd1]/usr/lib/libruby-1.9.1.so.1.9(+0x73daa) [0x7faa1a2f4daa]/usr/lib/libruby-1.9.1.so.1.9(ruby_init+0xb5) [0x7faa1a2dddd5]ruby() [0x4007c6]/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7faa19ee47ed]ruby() [0x400809]-- Other runtime information -----------------------------------------------0: can't convert false into String (TypeError)]
-- | --





```

Why is this?

**Comment by toubib** [comment]
I'm not sure if the issue is with check-webpage or ruby 1.9. It may be possible that check-webpage is not compatible with ruby 1.9 anymore, I use it with ruby 2.2 on my (old) systems. You can quite easily install a new ruby version with https://github.com/rbenv/rbenv

Another solution: I made a rewrite of this project in Go here https://github.com/toubib/elmo and never really published it, but it's functional and really more easy to run, I could release it with binaries if you are interested.

**Comment by rduffner** [comment]
Hi,

thanks for answering so fast.

If you wanted to release a binary version of "elmo", I will test it.

I will also try installing a newer version of ruby.

**Comment by toubib** [comment]
Hi,

You can find a quick build (linux amd64) here: https://github.com/toubib/elmo/releases/tag/0.1-rc1
